server:
  port: 8081

resource:
  producer-host: http://localhost:8080
  tasks: ${resource.producer-host}/api/tasks
  users: ${resource.producer-host}/api/users
  pictures: ${resource.producer-host}/api/picture
